export var horseNames = [
    "Lunar Punchdrunk Neanderthal",
    "Massive Bastard Pride",
    "Wally's Wimpy Terminator",
    "Mr. Groovy Wizard",
    "Evil And Brisket",
    "Favorite Bender",
    "Sleepy Humbled",
    "Endless Musty Salesman",
    "Major Jumpy Clown",
    "All Tornado Rascal",
    "Galloping Pocket Full Of Roommate",
    "Mrs. Robinson's Missing Brisket",
    "All Perfect Roommate",
    "Near Death Unkempt Biology",
    "Whistling Punchdrunk Missing",
    "Loose-Lipped Missing",
    "I Shot The Belch Wizard",
    "Buster's Perfect Slop",
    "Wally's Comedy",
    "Flummoxed Action Storm",
    "Who Took The Grave Filibuster",
    "Tammie's In Science",
    "Bring the Dancing Comedy",
    "Stumbling Halloween",
    "Loose Grave Wizard",
    "Mister Backyard Hallucination",
    "Stupid Meatloaf",
    "Exceptional Bored Stray",
    "Where's Jumpy Clown",
    "Where's Thunder Comedy",
    "Tammie's Favorite Meatloaf",
    "Exceptional Jumpy Underwater",
    "Near Death Perfect Smoke",
    "Stupid Pocket Full Of Grooming",
    "Who Took The Belch Tropic",
    "Romantic Imaginary Holiday",
    "Justine's Coal Miner's Brassiere",
    "In It For Pocket Full Of Underground",
    "Lonely Raw Holiday",
    "Major Groovy Soul"
];